version: "3"
services:
  nemesis:
    build:
      context: ./nemesis
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
      - ./nemesis/src:/opt/app/src
      - ./nemesis/public:/opt/app/public
  stormbreaker:
    build:
      context: ./stormbreaker
      dockerfile: Dockerfile-dev
    ports:
      - "5000:5000"
